name: Submit a library!
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/submit-library.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > submitlibrary.json

      - run: cat submitlibrary.json

      - run: node ./run_submission_library.js

      - name: Commit changes
        shell: bash
        env:
          SRC_FOLDER_PATH: '*'
          TARGET_BRANCH: 'content'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add . && \
          git commit -m 'Submitted library!' && \
          git push
      - uses: peter-evans/close-issue@v1
        with:
          comment: Library has been submitted! Please wait a few minutes while we prepare your page before visiting <a href="https://gamemakerkitchen.com/">https://gamemakerkitchen.com/</a>!